tuple=()
tuple1=("hello","welcome",'hi')
print(type(tuple1))
print(tuple1+(1,2))
print(len(tuple1))
print(tuple1.count('l'))
print(max(tuple1))
print(min(tuple1))
print('hi' in tuple1)
(x,y,z)=(43,51,"hello")
print(y)
